In [ ]:
from google.colab import files
uploaded = files.upload()

Saving cleaned_ewaste_dataset.csv to cleaned_ewaste_dataset.csv


In [ ]:
import pandas as pd

df = pd.read_csv("cleaned_ewaste_dataset.csv")

df.head()

,Item,Category,Gold,Silver,Platinum,Rhodium,Nickel,Tin,Lithium,Aluminum,Carbon,Profit ($)
0,iPhone 11,Cat3,3.58,2.95,1.73,8.92,1.91,1.01,1.82,1.27,9.51,270
1,Toaster,Cat2,7.21,4.31,6.21,5.63,9.59,7.65,0.51,3.03,4.22,689
2,Speaker,Cat4,8.91,5.09,2.42,7.70,1.09,1.49,7.42,3.63,8.83,570
3,Microwave Oven,Cat2,2.62,3.84,2.98,7.66,9.41,2.25,7.84,6.18,6.36,290
4,Air Conditioner,Cat1,3.47,3.89,6.20,4.35,5.07,8.65,8.62,0.82,5.53,505


In [ ]:
df.shape

(10000, 12)

In [ ]:
df.columns

Index(['Item', 'Category', 'Gold', 'Silver', 'Platinum', 'Rhodium', 'Nickel',
       'Tin', 'Lithium', 'Aluminum', 'Carbon', 'Profit ($)'],
      dtype='object')

In [ ]:
df.head()

,Item,Category,Gold,Silver,Platinum,Rhodium,Nickel,Tin,Lithium,Aluminum,Carbon,Profit ($)
0,iPhone 11,Cat3,3.58,2.95,1.73,8.92,1.91,1.01,1.82,1.27,9.51,270
1,Toaster,Cat2,7.21,4.31,6.21,5.63,9.59,7.65,0.51,3.03,4.22,689
2,Speaker,Cat4,8.91,5.09,2.42,7.70,1.09,1.49,7.42,3.63,8.83,570
3,Microwave Oven,Cat2,2.62,3.84,2.98,7.66,9.41,2.25,7.84,6.18,6.36,290
4,Air Conditioner,Cat1,3.47,3.89,6.20,4.35,5.07,8.65,8.62,0.82,5.53,505


In [ ]:
df.isnull().sum()

,0
Item,0
Category,0
Gold,0
Silver,0
Platinum,0
Rhodium,0
Nickel,0
Tin,0
Lithium,0
Aluminum,0


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Item        10000 non-null  object 
 1   Category    10000 non-null  object 
 2   Gold        10000 non-null  float64
 3   Silver      10000 non-null  float64
 4   Platinum    10000 non-null  float64
 5   Rhodium     10000 non-null  float64
 6   Nickel      10000 non-null  float64
 7   Tin         10000 non-null  float64
 8   Lithium     10000 non-null  float64
 9   Aluminum    10000 non-null  float64
 10  Carbon      10000 non-null  float64
 11  Profit ($)  10000 non-null  int64  
dtypes: float64(9), int64(1), object(2)
memory usage: 937.6+ KB


In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.describe()

,Gold,Silver,Platinum,Rhodium,Nickel,Tin,Lithium,Aluminum,Carbon,Profit ($)
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,5.058206,5.001442,5.055381,5.086352,5.032354,5.023587,5.006292,5.001327,5.032132,521.949800
std,2.863858,2.855341,2.851408,2.838022,2.866194,2.856320,2.861186,2.850100,2.867471,208.521349
min,0.100000,0.100000,0.100000,0.100000,0.100000,0.100000,0.100000,0.100000,0.100000,21.000000
25%,2.590000,2.530000,2.590000,2.640000,2.530000,2.510000,2.540000,2.560000,2.550000,372.750000
50%,5.060000,4.970000,5.050000,5.110000,5.000000,5.040000,4.960000,4.990000,5.000000,524.000000
75%,7.570000,7.470000,7.562500,7.530000,7.560000,7.520000,7.470000,7.450000,7.510000,671.000000
max,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,1028.000000


In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Category'] = le.fit_transform(df['Category'])

In [ ]:
df = df.drop("Item", axis=1)

In [ ]:
import numpy as np

your_threshold_value = 500 # Example threshold, please define based on your analysis
df['Recovery_Status'] = np.where(df['Profit ($)'] > your_threshold_value, 'Recoverable', 'Non-recoverable')

df.head()

,Category,Gold,Silver,Platinum,Rhodium,Nickel,Tin,Lithium,Aluminum,Carbon,Profit ($),Recovery_Status
0,2,3.58,2.95,1.73,8.92,1.91,1.01,1.82,1.27,9.51,270,Non-recoverable
1,1,7.21,4.31,6.21,5.63,9.59,7.65,0.51,3.03,4.22,689,Recoverable
2,3,8.91,5.09,2.42,7.70,1.09,1.49,7.42,3.63,8.83,570,Recoverable
3,1,2.62,3.84,2.98,7.66,9.41,2.25,7.84,6.18,6.36,290,Non-recoverable
4,0,3.47,3.89,6.20,4.35,5.07,8.65,8.62,0.82,5.53,505,Recoverable


In [ ]:
df['Recyclable'] = (df['Profit ($)'] > 300).astype(int)

In [ ]:
X = df.drop(['Profit ($)', 'Recyclable'], axis=1)
y = df['Recyclable']

In [ ]:
 df['Recovery_Status'] = df['Recovery_Status'].map({
    'Recyclable': 1,
    'Non-Recyclable': 0
})

In [ ]:
df['Recovery_Status'].unique()

array([nan])

In [ ]:
df['Recovery_Status'].unique()

array([nan])

In [ ]:
import pandas as pd
df = pd.read_csv("cleaned_ewaste_dataset.csv")

In [ ]:
df['Recovery_Status'].unique()

array([0, 1])

In [ ]:
df.isnull().sum()

,0
Category,0
Gold,0
Silver,0
Platinum,0
Rhodium,0
Nickel,0
Tin,0
Lithium,0
Aluminum,0
Carbon,0


In [ ]:
X = df.drop('Recovery_Status', axis=1)
y = df['Recovery_Status']

In [ ]:
df.head()

,Category,Gold,Silver,Platinum,Rhodium,Nickel,Tin,Lithium,Aluminum,Carbon,Profit ($),Recovery_Status,Recyclable
0,2,3.58,2.95,1.73,8.92,1.91,1.01,1.82,1.27,9.51,270,0,0
1,1,7.21,4.31,6.21,5.63,9.59,7.65,0.51,3.03,4.22,689,1,1
2,3,8.91,5.09,2.42,7.70,1.09,1.49,7.42,3.63,8.83,570,1,1
3,1,2.62,3.84,2.98,7.66,9.41,2.25,7.84,6.18,6.36,290,0,0
4,0,3.47,3.89,6.20,4.35,5.07,8.65,8.62,0.82,5.53,505,1,1


In [ ]:
df['Non_Recyclable'] = 1 - df['Recyclable']

In [ ]:
df.head()

,Category,Gold,Silver,Platinum,Rhodium,Nickel,Tin,Lithium,Aluminum,Carbon,Profit ($),Recovery_Status,Recyclable,Non_Recyclable
0,2,3.58,2.95,1.73,8.92,1.91,1.01,1.82,1.27,9.51,270,0,0,1
1,1,7.21,4.31,6.21,5.63,9.59,7.65,0.51,3.03,4.22,689,1,1,0
2,3,8.91,5.09,2.42,7.70,1.09,1.49,7.42,3.63,8.83,570,1,1,0
3,1,2.62,3.84,2.98,7.66,9.41,2.25,7.84,6.18,6.36,290,0,0,1
4,0,3.47,3.89,6.20,4.35,5.07,8.65,8.62,0.82,5.53,505,1,1,0


In [ ]:
df['Recyclable'] = 1 - df['Recyclable']

In [ ]:
df['Non_Recyclable'] = 1 - df['Recyclable']

In [ ]:
df[['Recyclable','Non_Recyclable']].head()

,Recyclable,Non_Recyclable
0,1,0
1,0,1
2,0,1
3,1,0
4,0,1


In [ ]:
df.head()

,Category,Gold,Silver,Platinum,Rhodium,Nickel,Tin,Lithium,Aluminum,Carbon,Profit ($),Recovery_Status,Recyclable,Non_Recyclable
0,2,3.58,2.95,1.73,8.92,1.91,1.01,1.82,1.27,9.51,270,0,1,0
1,1,7.21,4.31,6.21,5.63,9.59,7.65,0.51,3.03,4.22,689,1,0,1
2,3,8.91,5.09,2.42,7.70,1.09,1.49,7.42,3.63,8.83,570,1,0,1
3,1,2.62,3.84,2.98,7.66,9.41,2.25,7.84,6.18,6.36,290,0,1,0
4,0,3.47,3.89,6.20,4.35,5.07,8.65,8.62,0.82,5.53,505,1,0,1


In [ ]:
df.to_csv("ewaste_final_dataset.csv", index=False)

In [ ]:
from google.colab import files
files.download("ewaste_final_dataset.csv")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>